version: '3'


#env:
#  host: 192.168.1.1
#  user: root
#  privateKey: .ssh/id_rsa


tasks:
  hello:
    cmds:
      - ifconfig
      - ls /var/log/

  install_nginx:
    cmds:
      - apt update
      - apt install -y nginx
