version: '3'


#envs vars
ENV_HOST: 192.168.1.1
ENV_USER: root
ENV_PRIVATEKEY: .ssh/id_rsa
#ENV_PASSWORD: password
#ENV_PORT: 22
#ENV_SILENT: false


tasks:
  hello:
    cmds:
      - ifconfig
      - ls /var/log/

  install_nginx:
    cmds:
      - apt update
      - apt install -y nginx
